### ISSUE TITLE
Integração na prática com o Rocketchat privado

### ISSUE THREAD

**Issue by viniciusbarretobr** [samuelrbo/rocketchat-whatsapp#3]
Olá Samuel, parabéns por seu projeto.
Amigo, isto cabe para a integração com a API do Whatsapp Business? 
Você possui um passo a passo de como ativamos seu código em nosso VPS onde o rocketchat está rodando?
Obrigado e Abraço!

**Comment by samuelrbo** [comment]
Oi VInicios, no casso esse projeto é um plugin para o Chrome para utilizar o whatsapp web como interface para integrar com o RocketChat.

No caso do business existem 2 maneiras que você pode fazer:
1- Entrar em contato com o Facebook para ver a disponibilidade da API deles (Da última vez que entrei em contato a conta precisava ser business e você teria que ter uma interação de 500.000 msgs com os clientes)

2- Existe um projeto, o qual eu utilizo o js, que faz a ponte. Ele basicamente usa o selenium com a mesma lib JS q eu uso para fazer o meio de campo. Ele também integra com o whatsapp web, mas de uma maneira mais agradável, dando a possibilidade de criar uma API.

O projeto é em python e tem um exemplo usando o flask para montar uma API: https://github.com/mukulhase/WebWhatsapp-Wrapper/
